// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpsXC9aZoUsiKZML9g5lWO3VhuDgOkY1w',
    appId: '1:286859342101:web:0ccf361938ce4d2a3b391c',
    messagingSenderId: '286859342101',
    projectId: 'spinwheel-ee5cd',
    authDomain: 'spinwheel-ee5cd.firebaseapp.com',
    databaseURL: 'https://spinwheel-ee5cd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spinwheel-ee5cd.appspot.com',
    measurementId: 'G-NEM8D06K37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrwVWSo7nPANVN3XuJfGbf7-vJ9fAo2-o',
    appId: '1:286859342101:android:e76115d056029e573b391c',
    messagingSenderId: '286859342101',
    projectId: 'spinwheel-ee5cd',
    databaseURL: 'https://spinwheel-ee5cd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spinwheel-ee5cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4zs8a1LxmnobE8P-gQlqiLJ4F9EYna8A',
    appId: '1:286859342101:ios:55782b10adc2876e3b391c',
    messagingSenderId: '286859342101',
    projectId: 'spinwheel-ee5cd',
    databaseURL: 'https://spinwheel-ee5cd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spinwheel-ee5cd.appspot.com',
    iosBundleId: 'com.example.spinwheel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4zs8a1LxmnobE8P-gQlqiLJ4F9EYna8A',
    appId: '1:286859342101:ios:55782b10adc2876e3b391c',
    messagingSenderId: '286859342101',
    projectId: 'spinwheel-ee5cd',
    databaseURL: 'https://spinwheel-ee5cd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spinwheel-ee5cd.appspot.com',
    iosBundleId: 'com.example.spinwheel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpsXC9aZoUsiKZML9g5lWO3VhuDgOkY1w',
    appId: '1:286859342101:web:ce9cbe97c831bd773b391c',
    messagingSenderId: '286859342101',
    projectId: 'spinwheel-ee5cd',
    authDomain: 'spinwheel-ee5cd.firebaseapp.com',
    databaseURL: 'https://spinwheel-ee5cd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spinwheel-ee5cd.appspot.com',
    measurementId: 'G-E8HSNMNMK8',
  );
}
