// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7H2Ex5jFtZTGVQPxhY3LTaUlm1K9ylXQ',
    appId: '1:748562652968:web:20367f1ec20a66763c3a1d',
    messagingSenderId: '748562652968',
    projectId: 'slot-machine-8c7f7',
    authDomain: 'slot-machine-8c7f7.firebaseapp.com',
    storageBucket: 'slot-machine-8c7f7.appspot.com',
    measurementId: 'G-QVQSHVQERM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAS1_HJb3fMtka49goy3az1E1eu1ZLCCg',
    appId: '1:748562652968:android:a3e88650a2d59e313c3a1d',
    messagingSenderId: '748562652968',
    projectId: 'slot-machine-8c7f7',
    storageBucket: 'slot-machine-8c7f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_RmzQkhpndkmkPDXf49luaArfNmEd9oQ',
    appId: '1:748562652968:ios:0db7223edb5409043c3a1d',
    messagingSenderId: '748562652968',
    projectId: 'slot-machine-8c7f7',
    storageBucket: 'slot-machine-8c7f7.appspot.com',
    iosBundleId: 'com.example.arcadeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_RmzQkhpndkmkPDXf49luaArfNmEd9oQ',
    appId: '1:748562652968:ios:0db7223edb5409043c3a1d',
    messagingSenderId: '748562652968',
    projectId: 'slot-machine-8c7f7',
    storageBucket: 'slot-machine-8c7f7.appspot.com',
    iosBundleId: 'com.example.arcadeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7H2Ex5jFtZTGVQPxhY3LTaUlm1K9ylXQ',
    appId: '1:748562652968:web:20367f1ec20a66763c3a1d',
    messagingSenderId: '748562652968',
    projectId: 'slot-machine-8c7f7',
    authDomain: 'slot-machine-8c7f7.firebaseapp.com',
    storageBucket: 'slot-machine-8c7f7.appspot.com',
    measurementId: 'G-QVQSHVQERM',
  );
}
