// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz6PP3DCDsTkok8mR5w98gqpH-ccJQHus',
    appId: '1:667574110438:web:dc427f8a1a78e83613d327',
    messagingSenderId: '667574110438',
    projectId: 'arcade-68d28',
    authDomain: 'arcade-68d28.firebaseapp.com',
    storageBucket: 'arcade-68d28.appspot.com',
    measurementId: 'G-5SBSH7VR9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACXBnNiTWvYVLwlmltTjZxsISyza-U-O8',
    appId: '1:667574110438:android:ad7db636d9241db013d327',
    messagingSenderId: '667574110438',
    projectId: 'arcade-68d28',
    storageBucket: 'arcade-68d28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsWOmv1fSn88hIrbDMrZ_EsxdnDmFg6bc',
    appId: '1:667574110438:ios:dcc94a25afe14b2d13d327',
    messagingSenderId: '667574110438',
    projectId: 'arcade-68d28',
    storageBucket: 'arcade-68d28.appspot.com',
    iosBundleId: 'com.example.arcadeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsWOmv1fSn88hIrbDMrZ_EsxdnDmFg6bc',
    appId: '1:667574110438:ios:dcc94a25afe14b2d13d327',
    messagingSenderId: '667574110438',
    projectId: 'arcade-68d28',
    storageBucket: 'arcade-68d28.appspot.com',
    iosBundleId: 'com.example.arcadeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz6PP3DCDsTkok8mR5w98gqpH-ccJQHus',
    appId: '1:667574110438:web:0c6050e2bdac3b2113d327',
    messagingSenderId: '667574110438',
    projectId: 'arcade-68d28',
    authDomain: 'arcade-68d28.firebaseapp.com',
    storageBucket: 'arcade-68d28.appspot.com',
    measurementId: 'G-YBQBXVEQW3',
  );

}